services:
  traefik:
    # Fixed name in dev for easier debugging
    container_name: devops_traefik
    ports:
      # Traefik dashboard directly accessible without going through the domain
      - "8080:8080"

  postgres:
    # Fixed name in dev for easier debugging
    container_name: devops_postgres
    ports:
      # Direct access to PostgreSQL from IDE or client like DBeaver/TablePlus
      - "5432:5432"

  redis:
    # Fixed name in dev for easier debugging
    container_name: devops_redis
    ports:
      # Direct access to Redis from a client like RedisInsight
      - "6379:6379"

  mailhog:
    # Fixed name in dev for easier debugging
    container_name: devops_mailhog
    ports:
      # SMTP port to send emails from outside the Docker network
      - "1025:1025"
      # MailHog web UI directly accessible without going through the domain
      - "8025:8025"

  adminer:
    # Fixed name in dev for easier debugging
    container_name: devops_adminer
    ports:
      # Adminer directly accessible without going through the domain
      - "8081:8080"

  frontend:
    # Fixed name in dev for easier debugging
    container_name: devops_frontend
    ports:
      # Frontend directly accessible without going through Traefik
      - "5173:8080"

  prometheus:
    # Fixed name in dev for easier debugging
    container_name: devops_prometheus
    ports:
      # Prometheus UI directly accessible without going through the domain
      - "9090:9090"

  grafana:
    # Fixed name in dev for easier debugging
    container_name: devops_grafana
    ports:
      # Grafana UI directly accessible without going through the domain
      - "3001:3000"