services:
  postgres:
    image: postgres:16-alpine
    container_name: devops_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: devops_redis
    networks:
      - devops
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: devops_mailhog
    networks:
      - devops
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI web
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: devops_adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - devops

volumes:
  postgres_data:

networks:
  devops:
    driver: bridge